SELECT B.ID, B.NAME, COUNT(B.NAME) AS KINDS
FROM (SELECT EMP.ID, EMP.NAME, SEL.CAR_ID
      FROM EMPLOYEES AS EMP
      INNER JOIN SELLINGS AS SEL ON EMP.ID = SEL.EMPLOYEE_ID
      GROUP BY EMP.ID, SEL.CAR_ID
     ) AS B
GROUP BY B.NAME
HAVING KINDS >= 3
